--
-- File generated with SQLiteStudio v3.3.3 on tor. feb. 14 00:42:21 2023
--
-- Text encoding used: UTF-8
--
-- Results of query:
-- SELECT * FROM Team
-- WHERE Team.team_api_id IN (SELECT DISTINCT Team.team_api_id FROM Team JOIN Team_Attributes ON Team.team_api_id = Team_Attributes.team_api_id
-- WHERE (Team.id > 2510 AND Team.id < 26547) OR (Team.id > 41673 AND Team.id < 49115))
--
BEGIN TRANSACTION;

CREATE TABLE Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name);
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (11822, 4087, 111271, 'Évian Thonon Gaillard FC', 'ETG');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (10312, 4170, 111376, 'US Boulogne Cote D''Opale', 'BOU');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (22805, 6269, 112225, 'Novara', 'NOV');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (14876, 6391, 110316, 'GFC Ajaccio', 'GAJ');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (12594, 7794, 58, 'SC Bastia', 'BAS');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9540, 7819, 210, 'SM Caen', 'CAE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (47612, 7869, 1867, 'Córdoba CF', 'COR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (45330, 7878, 110832, 'Granada CF', 'GRA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (24288, 7943, 111974, 'Sassuolo', 'SAS');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (14868, 8121, 1530, 'Angers SCO', 'ANG');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (16850, 8152, 110329, 'FC St. Pauli', 'STP');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (16239, 8165, 171, '1. FC Nürnberg', 'NUR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15626, 8177, 166, 'Hertha BSC Berlin', 'HBE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15619, 8178, 32, 'Bayer 04 Leverkusen', 'LEV');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (4234, 8191, 1796, 'Burnley', 'BUR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (18074, 8194, 110636, 'Fortuna Düsseldorf', 'FDU');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (8021, 8197, 95, 'Leicester City', 'LEI');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15630, 8226, 10029, 'TSG 1899 Hoffenheim', 'HOF');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (19916, 8234, 111239, 'FC Ingolstadt 04', 'ING');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (19917, 8262, 110502, 'SV Darmstadt 98', 'DAR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15633, 8295, 1832, 'Karlsruher SC', 'KAR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43044, 8302, 481, 'Sevilla FC', 'SEV');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43046, 8305, 1860, 'Getafe CF', 'GET');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (48358, 8306, 472, 'UD Las Palmas', 'LAS');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43051, 8315, 448, 'Athletic Club de Bilbao', 'BIL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (7276, 8344, 1961, 'Cardiff City', 'CAR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (16848, 8350, 29, '1. FC Kaiserslautern', 'KAI');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (18079, 8357, 165, 'SpVgg Greuther Fürth', 'GRF');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (16237, 8358, 25, 'SC Freiburg', 'FRE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (45333, 8370, 480, 'Rayo Vallecano', 'RAY');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43037, 8371, 479, 'CA Osasuna', 'OSA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (47605, 8372, 467, 'SD Eibar', 'EIB');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43041, 8388, 477, 'CD Numancia', 'NUM');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43803, 8394, 244, 'Real Zaragoza', 'ZAR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15629, 8398, 162, 'FC Energie Cottbus', 'COT');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (17465, 8406, 100409, 'FC Augsburg', 'AUG');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3475, 8455, 5, 'Chelsea', 'CHE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3466, 8456, 10, 'Manchester City', 'MCI');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (19305, 8460, 10030, 'SC Paderborn 07', 'PAD');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3476, 8462, 1790, 'Portsmouth', 'POR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (6504, 8466, 17, 'Southampton', 'SOU');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3461, 8472, 106, 'Sunderland', 'SUN');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43048, 8479, 571, 'RC Recreativo', 'HUE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9549, 8481, 1823, 'AS Nancy-Lorraine', 'NAN');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (4996, 8483, 1926, 'Blackpool', 'BLA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (11076, 8521, 378, 'Stade Brestois 29', 'BRE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20513, 8524, 39, 'Atalanta', 'ATA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3464, 8528, 1917, 'Wigan Athletic', 'WIG');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20515, 8529, 1842, 'Cagliari', 'CAG');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20517, 8530, 110364, 'Catania', 'CAT');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20519, 8533, 192, 'Chievo Verona', 'CHI');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (25048, 8534, 1746, 'Empoli', 'EMP');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20521, 8535, 110374, 'Fiorentina', 'FIO');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (21285, 8537, 1844, 'Livorno', 'LIV');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20532, 8540, 1843, 'Palermo', 'PAL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20516, 8543, 46, 'Lazio', 'LAZ');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3469, 8549, 12, 'Middlesbrough', 'MID');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (14106, 8550, 68, 'FC Metz', 'MET');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20514, 8551, 1838, 'Siena', 'SIE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43049, 8558, 452, 'RCD Espanyol', 'ESP');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3471, 8559, 4, 'Bolton Wanderers', 'BOL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (44569, 8560, 457, 'Real Sociedad', 'SOC');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20523, 8564, 47, 'Milan', 'ACM');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (11817, 8576, 614, 'AC Ajaccio', 'AJA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (44565, 8581, 1853, 'Levante UD', 'LEV');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9537, 8583, 57, 'AJ Auxerre', 'AUX');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3470, 8586, 18, 'Tottenham Hotspur', 'TOT');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (10300, 8588, 64, 'RC Lens', 'LEN');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9552, 8592, 219, 'Olympique de Marseille', 'MAR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20531, 8600, 55, 'Udinese', 'UDI');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (4225, 8602, 110, 'Wolverhampton Wanderers', 'WOL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43047, 8603, 449, 'Real Betis Balompié', 'BET');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43040, 8633, 243, 'Real Madrid CF', 'REA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43042, 8634, 241, 'FC Barcelona', 'BAR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20528, 8636, 44, 'Inter', 'INT');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9550, 8639, 65, 'LOSC Lille', 'LIL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3462, 8650, 9, 'Liverpool', 'LIV');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3463, 8654, 19, 'West Ham United', 'WHU');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3468, 8655, 3, 'Blackburn Rovers', 'BLB');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (4218, 8658, 88, 'Birmingham City', 'BIR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3460, 8659, 109, 'West Bromwich Albion', 'WBA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43036, 8661, 453, 'RCD Mallorca', 'MAL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3473, 8667, 1952, 'Hull City', 'HUL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3467, 8668, 7, 'Everton', 'EVE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (8779, 8678, 1943, 'Bournemouth', 'BOU');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9543, 8682, 1739, 'Le Mans FC', 'LEM');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20525, 8686, 52, 'Roma', 'ROM');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9544, 8689, 217, 'FC Lorient', 'LOR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20520, 8690, 203, 'Reggio Calabria', 'REG');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43043, 8696, 456, 'Racing Santander', 'SAN');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15628, 8697, 38, 'SV Werder Bremen', 'WBR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15623, 8721, 175, 'VfL Wolfsburg', 'WOL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15624, 8722, 31, '1. FC Köln', 'FCK');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9541, 9746, 1738, 'Le Havre AC', 'LEH');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (13343, 9747, 62, 'En Avant de Guingamp', 'GUI');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9545, 9748, 66, 'Olympique Lyonnais', 'LYO');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (18691, 9776, 110500, 'Eintracht Braunschweig', 'BRA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43039, 9783, 242, 'RC Deportivo de La Coruña', 'COR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15631, 9788, 23, 'Borussia Mönchengladbach', 'GLA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15620, 9789, 22, 'Borussia Dortmund', 'DOR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15618, 9790, 28, 'Hamburger SV', 'HAM');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (6509, 9798, 1793, 'Reading', 'REA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20529, 9804, 54, 'Torino', 'TOR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15625, 9810, 1824, 'Eintracht Frankfurt', 'EFR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (8784, 9817, 1795, 'Watford', 'WAT');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15617, 9823, 21, 'FC Bayern Munich', 'BMU');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3459, 9825, 1, 'Arsenal', 'ARS');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (7261, 9826, 1799, 'Crystal Palace', 'CRY');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9539, 9827, 59, 'Girondins de Bordeaux', 'BOR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9547, 9829, 69, 'AS Monaco', 'MON');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9538, 9830, 71, 'FC Nantes', 'NAN');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9542, 9831, 72, 'OGC Nice', 'NIC');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (11825, 9836, 110569, 'Dijon FCO', 'DIJ');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (12587, 9837, 379, 'Stade de Reims', 'REI');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9548, 9847, 73, 'Paris Saint-Germain', 'PSG');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (5756, 9850, 1792, 'Norwich City', 'NOR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9551, 9851, 74, 'Stade Rennais FC', 'REN');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9556, 9853, 1819, 'AS Saint-Étienne', 'ETI');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9554, 9855, 1805, 'Grenoble Foot 38', 'GRE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20524, 9857, 189, 'Bologna', 'BOL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (22044, 9858, 190, 'Brescia', 'BRE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43054, 9864, 573, 'Málaga CF', 'MAL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43052, 9865, 1861, 'UD Almería', 'ALM');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43804, 9867, 260, 'CD Tenerife', 'TEN');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43800, 9868, 1742, 'Xerez Club Deportivo', 'XER');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43045, 9869, 459, 'Real Sporting de Gijón', 'SPG');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9555, 9873, 110456, 'Valenciennes FC', 'VAL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9553, 9874, 226, 'FC Sochaux-Montbéliard', 'SOC');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20526, 9875, 48, 'Napoli', 'NAP');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (24273, 9876, 206, 'Hellas Verona', 'VER');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (23523, 9878, 200, 'Pescara', 'PES');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3474, 9879, 144, 'Fulham', 'FUL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (22042, 9880, 110915, 'Cesena', 'CES');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20527, 9882, 1837, 'Sampdoria', 'SAM');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20522, 9885, 45, 'Juventus', 'JUV');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20530, 9888, 347, 'Lecce', 'LEC');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (25791, 9891, 111657, 'Frosinone', 'FRO');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15622, 9904, 485, 'Hannover 96', 'HAN');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (16243, 9905, 169, '1. FSV Mainz 05', 'MAI');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43053, 9906, 240, 'Atlético Madrid', 'AMA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (46087, 9910, 450, 'RC Celta de Vigo', 'CEL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15634, 9911, 160, 'VfL Bochum', 'BOC');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15627, 9912, 159, 'DSC Arminia Bielefeld', 'BIE');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (9546, 9941, 1809, 'Toulouse FC', 'TOU');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (21280, 9976, 1848, 'Bari', 'BAR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (5744, 10003, 1960, 'Swansea City', 'SWA');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (21292, 10167, 50, 'Parma', 'PAR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (5747, 10172, 15, 'Queens Park Rangers', 'QPR');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15621, 10189, 34, 'FC Schalke 04', 'S04');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3472, 10194, 1806, 'Stoke City', 'STK');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43038, 10205, 483, 'Villarreal CF', 'VIL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (20518, 10233, 110556, 'Genoa', 'GEN');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (12595, 10242, 294, 'ES Troyes AC', 'TRO');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (10309, 10249, 70, 'Montpellier Hérault SC', 'MON');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3465, 10252, 2, 'Aston Villa', 'AVL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3457, 10260, 11, 'Manchester United', 'MUN');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (3458, 10261, 13, 'Newcastle United', 'NEW');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43035, 10267, 461, 'Valencia CF', 'VAL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (46848, 10268, 468, 'Elche CF', 'ELC');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (15632, 10269, 36, 'VfB Stuttgart', 'STU');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (44557, 10278, 100879, 'Hércules Club de Fútbol', 'HER');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (43050, 10281, 462, 'Real Valladolid', 'VAL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (11074, 108893, 111989, 'AC Arles-Avignon', 'ARL');
INSERT INTO Team (id, team_api_id, team_fifa_api_id, team_long_name, team_short_name) VALUES (25804, 208931, 112409, 'Carpi', 'CAP');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
